# permissions for end users to view grids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: paddy
    app.kubernetes.io/managed-by: kustomize
  name: grid-viewer-role
rules:
- apiGroups:
  - paddy.io
  resources:
  - grids
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paddy.io
  resources:
  - grids/status
  verbs:
  - get
