# permissions for end users to edit grids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: paddy
    app.kubernetes.io/managed-by: kustomize
  name: grid-editor-role
rules:
- apiGroups:
  - paddy.github.com
  resources:
  - grids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paddy.github.com
  resources:
  - grids/status
  verbs:
  - get
