---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - paddy.github.com
  resources:
  - grids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paddy.github.com
  resources:
  - grids/finalizers
  verbs:
  - update
- apiGroups:
  - paddy.github.com
  resources:
  - grids/status
  verbs:
  - get
  - patch
  - update
