apiVersion: paddy.io/v1
kind: Grid
metadata:
  labels:
    app.kubernetes.io/name: paddy
    app.kubernetes.io/managed-by: kustomize
  name: grid-sample
spec:
  service:
    name: details
    portName: http
    port: 9080
    targetPort: "9080"
  targetRef:
    name: details-v1
    kind: Deployment
    apiVersion: apps/v1
  # TODO(user): Add fields here
