apiVersion: paddy.io/v1
kind: Grid
metadata:
  labels:
    app.kubernetes.io/name: paddy
    app.kubernetes.io/managed-by: kustomize
  name: grid-sample
spec:
  services:
    - name: details
      portName: http
      port: 9080
      targetPort: "9080"
  targetRef:
    name: details-v2
    kind: Deployment
    apiVersion: apps/v1
  # TODO(user): Add fields here
