apiVersion: paddy.github.com/v1
kind: RolloutBox
metadata:
  labels:
    app.kubernetes.io/name: paddy
    app.kubernetes.io/managed-by: kustomize
  name: rolloutbox-sample
spec:
  # TODO(user): Add fields here
